name: Build Geode Mod
on: [workflow_dispatch, push]

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Forzamos 'Android' aquí. Si falla, el problema es el mod.json
          target: Android
          # Usamos nightly para soportar versiones nuevas de GD
          sdk: nightly
          combine: true
          
