name: Build Geode Mod
on: [workflow_dispatch, push]

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Al usar 'Android' (sin el 32), la acción moderna 
          # instala automáticamente el SDK y compila para 32 y 64 bits.
          target: Android
          sdk: nightly
          combine: true
          
